language: ruby
rvm:
- 2.1.1
- 1.9.3
cache: bundler
addons:
  postgresql: '9.3'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
notifications:
  campfire:
    rooms:
      secure: A6W7X2wP+pSjcvHP7Pg0nKvSEtAK1Z3KF1CjO0HFfvLGMuSjbXVhYtVSy+SqXBOEW0w4vNyWsuEYrqHADsmxWDCBxRrag+r3AR90kouzbK86gSvzz8WrqUEva5jH5Q8cCeB6vtU7AMqXouzvU6HheMu0q8fIVJvWZqlLC9s44NU=
