language: ruby
rvm:
- 2.2.0
cache: bundler
addons:
  postgresql: '9.3'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
notifications:
  campfire:
    rooms:
      secure: fD1kclF+hrPaVy/4Mwm8M/faV0sNs/qPHBpyr/dbLwcDWNcJJ61iZKKAarkviGMGwm2bHg3Uct4t9QNBiwFmwcafuzj03QTKPhj6KgZIWdm2sUn/vas44I5KJZe8SmduKvnRAgVwNRFdCNsObHUd2jgAMAQnQIRqcmpWJhJ/18M=
  slack:
    secure: Td0sccIww1/h0tJq019ZTjsExIO5Xh+jmd6BL3UV98R8TYsPVVsqLCSgLmSV0NMv90JyDQvTxdVfWIF+MaA2xVnKw1ClJOGBQsQ920hZ+2AcXO+2jL+IGlVSQ0+tIRNw9Q3be1srVugRVs2+8D9I++0mnvMLWkzyT/E5lcpx9Rg=
